trigger: none
pool: Babaji

stages:
  - stage: stage1
    displayName: welcome stage 1
    
    jobs:
      - job: job1
        displayName: welcome to job 1
        steps:
        - task: CmdLine@2
          displayName: Welcome to Valenta 
          inputs:
            script: |
              echo Write your commands here
              
              echo Hello world


  - stage: stage2
    displayName: welcome stage 2
    jobs:
      - job: job2
        displayName: welcome to job 2
        steps:
        - task: CmdLine@2
          inputs:
            script: |
              echo Write your commands here
              
              echo Hello world

  - stage: stage3
    displayName: welcome stage 3
    jobs:
      - job: job3
        displayName: welcome to job 3
        steps:

        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            backendServiceArm: 'ado-cicd'
            backendAzureRmResourceGroupName: 'stgforbackend'
            backendAzureRmStorageAccountName: 'stgforbackend'
            backendAzureRmContainerName: 'container'
            backendAzureRmKey: 'yash.tfstate'

        - task: TerraformTask@5
          displayName: terraform plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)Environment/Dev'
            environmentServiceNameAzureRM: 'ado-cicd'

       